#1 Has the network latency gone up since we switched internet service providers?

#variables -network_latency, isp

#hypothesis: 

#null - "There is no wolf"
#The network latency with the current isp is less than or equal to the latency with the previous isp.

#alternative - "There is a wolf"
#The network latency with the current isp is greater than the latency with the previous isp.

#true positive
#p value is below .05 or 5% 
#Its the outcome we expect, proves our hypothesis.
#reject null hypothesis.
#When comparing network latency with the two isp's, the p value was below 5% so we rejected the null hypothesis.

#true negative
#p value is above .05 or 5%
#Not the outcome we expect, does not prove hypothesis. 
#accept null hypothesis.
#When comparing network latency with the two isp's, the p value was above 5% so we accpeted the null hypothesis.

#type I error - "Villagers beleiving the boy when there was no wolf"
#rejecting null hypothesis incorrectly

#result is less than .5, but there is no increase in latency.

#type II error "Villagers not beleiving the boy when there was a wolf"
#rejecting alternative hypothesis incorrectly

#result is below .5, but there is an increase in latency. 



#website- sales website
#variables
#traffic and sales

#Hypothesis:
#Null
#The resdesign of the website has brought no changes to the amount of traffic or sales from it.

#Alternative
#The traffic and sales of the website have increased since it has been redesigned. 


#true positive
#p value is below .05 or 5% 
#Its the outcome we expect, proves our hypothesis.
#reject null hypothesis.

#The p value was below 5% after comparing traffic and sales data from the new website, so we rejected the null hypothesis.


#true negative
#p value is above .05 or 5%
#Not the outcome we expect, does not prove hypothesis. 
#accept null hypothesis.

#The p value was above 5% after comparing traffic and sales data from the new website, so we accepted the null hypothesis.


#type I error - "Villagers beleiving the boy when there was no wolf"
#rejecting null hypothesis incorrectly

#result is less than .5, but there is no increase in sales or traffic.

#type II error "Villagers not beleiving the boy when there was a wolf"
#rejecting alternative hypothesis incorrectly

#result is below .5, but there is an increase in sales and traffic. 





television ad
variables:

ad and sales

Hypothesis:

null
Since running the television ad our sales are less than or equal than before.

alternative:

since running the ad our sales have increased. 

#true positive
#p value is below .05 or 5% 
#Its the outcome we expect, proves our hypothesis.
#reject null hypothesis.

When comparing sales after the televison ad we found the p value to be less than 5%, so we rejected the null hypothesis.

#true negative
#p value is above .05 or 5%
#Not the outcome we expect, does not prove hypothesis. 
#accept null hypothesis.

When comparing sales after the television ad we found the p value to be greater than 5% and accepted the null hypothesis.

#type I error - "Villagers beleiving the boy when there was no wolf"
#rejecting null hypothesis incorrectly

#result is less than .5, but there is no increase in sales after the ad.

#type II error "Villagers not beleiving the boy when there was a wolf"
#rejecting alternative hypothesis incorrectly

#result is below .5, but there is an increase in sales after the ad.

T-test exercises

Ace Realty wants to determine whether the average time it takes to sell homes is different for its two offices. A sample of 40 sales from office #1 revealed a mean of 90 days and a standard deviation of 15 days. A sample of 50 sales from office #2 revealed a mean of 100 days and a standard deviation of 20 days. Use a .05 level of significance.

Mean of monthly sales of office #1 = Mean of monthly sales of office #2
Mean of monthly sales of office #1 != Mean of monthly sales of office #2

In [23]:
alpha = .05

o1_standard_dev =15
o1_sales_sample = 40
o1_sales_days_mean = 90


o1_sales = np.random.normal(o1_sales_days_mean, o1_standard_dev, size = (o1_sales_sample))


In [24]:
o2_standard_dev =20
o2_sales_sample = 50
o2_sales_days_mean = 100


o2_sales = np.random.normal(o2_sales_days_mean, o2_standard_dev, size = (o2_sales_sample))

In [25]:
t, p = stats.ttest_ind(o1_sales, o2_sales, equal_var = False)
t,p

(-2.360203455640397, 0.02049240644011964)

In [26]:
if p/2 > alpha:
    print("We fail to reject $H_{0}$")
elif t < 0:
    print("We fail to reject $H_{0}$")
else:
    print("We reject $H_{0}$")

We fail to reject $H_{0}$


Load the mpg dataset and use it to answer the following questions:

Is there a difference in fuel-efficiency in cars from 2008 vs 1999?
Are compact cars more fuel-efficient than the average car?
Do manual cars get better gas mileage than automatic cars?

In [2]:
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import seaborn as sns
import pandas as pd
from pydataset import data

In [4]:
mpg = data('mpg')
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

#Correlation Exercises

1. Use the telco_churn data. Does tenure correlate with monthly charges? Total charges? What happens if you control for phone and internet service?

In [44]:
url = "/Users/paulneil/codeup-data-science/python-exercises/Cust_Churn_Telco - Cust_Churn_Telco.csv"
df = pd.read_csv(url)
df =df.dropna()
df.head(3)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   

      PaymentMethod MonthlyCharges  TotalCharges  Churn  
0  Electronic check          29.85         29.85     No  
1      Mailed check          56.95       1889.50     No  
2      Mailed check          53.85        108.15    Yes  

[3 rows x 21 columns]

In [ ]:
sns.pairplot(df, corner=True)
plt.suptitle("sns.pairplot visualizes continuous variable relationships")
plt.show()

a. Does tenure correlate with monthly charges?

In [33]:
x = df.tenure
y =df.MonthlyCharges
corr, p = stats.pearsonr(x,y)
corr, p

(0.2478998562861525, 4.094044991483017e-99)

b. Does tenure correlate with total charges?

In [45]:
x = df.tenure
y = df.TotalCharges
corr, p = stats.pearsonr(x,y)
corr, p

(0.8258804609332093, 0.0)

In [49]:
newdf= df[df.InternetService == 'No']
x = newdf.tenure
y= newdf.MonthlyCharges
corr, p = stats.pearsonr(x,y)
corr, p

(0.34618773548574805, 4.896604599947503e-44)

In [104]:
newdf= df[df.InternetService == 'No']
x = newdf.tenure
y= newdf.TotalCharges
corr, p = stats.pearsonr(x,y)
corr, p

(0.9814648859044319, 0.0)

In [51]:
newdf= df[df.PhoneService == 'No']
x = newdf.tenure
y= newdf.MonthlyCharges
corr, p = stats.pearsonr(x,y)
corr, p

(0.5924298640568981, 1.1732739032893169e-65)

In [52]:
newdf= df[df.PhoneService == 'No']
x = newdf.tenure
y= newdf.TotalCharges
corr, p = stats.pearsonr(x,y)
corr, p

(0.9534228506954507, 0.0)

3. Use the employees database.
Is there a relationship between how long an employee has been with the company and their salary?
Is there a relationship between how long an employee has been with the company and the number of titles they have had?

In [54]:
from env import host, user, password

url = f'mysql+pymysql://{user}:{password}@{host}/employees'

In [173]:
employees =pd.read_sql('Select * FROM employees', url)
salaries =pd.read_sql('Select * FROM salaries', url)
dept_emp =pd.read_sql('Select * FROM dept_emp', url)
departments =pd.read_sql('Select * FROM departments', url)
dept_manager =pd.read_sql('Select * FROM dept_manager', url)
titles =pd.read_sql('Select * FROM titles', url)

Is there a relationship between how long an employee has been with the company and their salary?

In [ ]:
#@variables
employment_length
salary

In [93]:
salaries.head(5)

emp_no  salary   from_date     to_date
0   10001   60117  1986-06-26  1987-06-26
1   10001   62102  1987-06-26  1988-06-25
2   10001   66074  1988-06-25  1989-06-25
3   10001   66596  1989-06-25  1990-06-25
4   10001   66961  1990-06-25  1991-06-25

In [111]:
salaries['to_date'] = salaries.to_date.str.replace(r'(^.*9999.*$)', '2021-08-21')
salaries['from_date'] = salaries.to_date.astype(str)
salaries.head(5)

<ipython-input-111-71664762bbdf>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  salaries['to_date'] = salaries.to_date.str.replace(r'(^.*9999.*$)', '2021-08-21')


emp_no  salary   from_date     to_date
0   10001   60117  1987-06-26  1987-06-26
1   10001   62102  1988-06-25  1988-06-25
2   10001   66074  1989-06-25  1989-06-25
3   10001   66596  1990-06-25  1990-06-25
4   10001   66961  1991-06-25  1991-06-25

In [ ]:
salaries['from_date'] = pd.to_datetime(df['from_date'], format='%Y%m%d')
salaries

In [ ]:
df['diff_days'] = df['End_date'] - df['Start_date']
2
df['diff_days']=df['diff_days']/np.timedelta64(1,'D')

print(df)


In [ ]:
salaries['tenor'] = salaries['to_date'] - salaries['from_date']
#salaries['tenor']=df['tenor']/np.timedelta64(1,'D')
salaries.head() 

CHI-Square

1. Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.

In [135]:
d = {'Codeup_Student': [49, 1], 'Not_Codeup_Student': [20, 30]}
df = pd.DataFrame(d, index =['Uses_a_MacBook',
                                'Does_Not_Use_a_MacBook'])
df


Codeup_Student  Not_Codeup_Student
Uses_a_MacBook                      49                  20
Does_Not_Use_a_MacBook               1                  30

In [151]:
# crosstab for observed values between Attrition and Depts

n = observed.values.sum()

In [138]:
index = ['Mac','No_Mac']
columns = ['Codeup','Not_Codeup']
c1 = 50/100
c2 = 50/100
r1= 69/100
r2 = 31/100

expected = pd.DataFrame([[(c1*r1),(c2*r1)],[(c1*r2),(c2*r2)]],index = index, columns=columns )*n
expected


Codeup  Not_Codeup
Mac       0.69        0.69
No_Mac    0.31        0.31

In [152]:
chi2, p, degf, expected = stats.chi2_contingency(df)

In [153]:
p

1.4116760526193828e-09

In [154]:
expected

array([[34.5, 34.5],
       [15.5, 15.5]])

2.Choose another 2 categorical variables from the mpg dataset and perform a chi2
contingency table test with them. Be sure to state your null and alternative hypotheses.

In [155]:
mpg = data('mpg')
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [156]:
# how many categories we have in 'manufacturer' column? (hint: value_counts())
mpg.manufacturer.value_counts()

dodge         37
toyota        34
volkswagen    27
ford          25
chevrolet     19
audi          18
subaru        14
hyundai       14
nissan        13
honda          9
jeep           8
pontiac        5
mercury        4
land rover     4
lincoln        3
Name: manufacturer, dtype: int64

In [161]:
# crosstab for observed values between manufacturer and trans
observed = pd.crosstab(mpg.manufacturer, mpg.trans)
observed

trans         auto(av)  auto(l3)  auto(l4)  auto(l5)  auto(l6)  auto(s4)  \
manufacturer                                                               
audi                 2         0         0         5         0         0   
chevrolet            0         0        14         0         0         0   
dodge                0         1        16        11         2         0   
ford                 0         0        10         5         2         0   
honda                0         0         2         2         0         0   
hyundai              0         0         6         1         0         0   
jeep                 0         0         2         6         0         0   
land rover           0         0         2         0         0         0   
lincoln              0         0         2         0         1         0   
mercury              0         0         1         2         1         0   
nissan               3         0         3         1         0         0   
pontiac              0         0         4         0         0         1   
subaru               0         0         5         0         0         2   
toyota               0         1        11         4         0         0   
volkswagen           0         0         5         2         0         0   

trans         auto(s5)  auto(s6)  manual(m5)  manual(m6)  
manufacturer                                              
audi                 0         4           4           3  
chevrolet            0         2           0           3  
dodge                0         0           3           4  
ford                 0         0           7           1  
honda                0         0           4           1  
hyundai              0         0           6           1  
jeep                 0         0           0           0  
land rover           0         2           0           0  
lincoln              0         0           0           0  
mercury              0         0           0           0  
nissan               1         0           3           2  
pontiac              0         0           0           0  
subaru               0         0           7           0  
toyota               2         2          13           1  
volkswagen           0         6          11           3

In [166]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

In [167]:
p

7.163203875453806e-10

In [168]:
print('Observed\n')
print(observed.values)
print('---\nExpected\n')
print(expected.astype(int))
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 2  0  0  5  0  0  0  4  4  3]
 [ 0  0 14  0  0  0  0  2  0  3]
 [ 0  1 16 11  2  0  0  0  3  4]
 [ 0  0 10  5  2  0  0  0  7  1]
 [ 0  0  2  2  0  0  0  0  4  1]
 [ 0  0  6  1  0  0  0  0  6  1]
 [ 0  0  2  6  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  2  0  0]
 [ 0  0  2  0  1  0  0  0  0  0]
 [ 0  0  1  2  1  0  0  0  0  0]
 [ 3  0  3  1  0  0  1  0  3  2]
 [ 0  0  4  0  0  1  0  0  0  0]
 [ 0  0  5  0  0  2  0  0  7  0]
 [ 0  1 11  4  0  0  2  2 13  1]
 [ 0  0  5  2  0  0  0  6 11  3]]
---
Expected

[[ 0  0  6  3  0  0  0  1  4  1]
 [ 0  0  6  3  0  0  0  1  4  1]
 [ 0  0 13  6  0  0  0  2  9  3]
 [ 0  0  8  4  0  0  0  1  6  2]
 [ 0  0  3  1  0  0  0  0  2  0]
 [ 0  0  4  2  0  0  0  0  3  1]
 [ 0  0  2  1  0  0  0  0  1  0]
 [ 0  0  1  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0]
 [ 0  0  4  2  0  0  0  0  3  1]
 [ 0  0  1  0  0  0  0  0  1  0]
 [ 0  0  4  2  0  0  0  0  3  1]
 [ 0  0 12  5  0  0  0  2  8  2]
 [ 0  0  9  4  0  

3. Use the data from the employees database to answer these questions:

Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)

b. Is an employee's gender independent of whether or not they are or have been a manager?

In [196]:
stats.norm(40,15).cdf(5)


0.009815328628645334

In [197]:
#10% of customers take survey
#618 customers
#70 or more take it

stats.binom(618,.1).sf(69)

0.15107528710211096