In [2]:
import numpy as np
#Life w/o numpy to life with numpy

#Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#Use python's built in functionality/operators to determine the following:

In [ ]:
#Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
print(sum_of_a)

In [ ]:
#Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
print(min_of_a)

In [ ]:
#Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
print(max_of_a)

In [ ]:
#Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = ((sum_of_a)/len(a))
print(mean_of_a)

In [ ]:
#Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_a = 1
for x in a:
    product_of_a *= x  
print(product_of_a)
    

In [ ]:
#Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
square_of_a =[]
for x in a:
    square = square_of_a.append(x**2)
print(a)
print(square_of_a)

In [ ]:
#Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a =[]
for num in a:
    if num % 2 != 0:
        odds_in_a.append(num+1)
print(a)
print(odds_in_a)

In [ ]:
#Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a =[]
for num in a:  
    if num % 2 == 0:
        evens_in_a.append(num+1)
print(a)
print(evens_in_a)

In [3]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, 
#sum, product, and list of squares for this list of two lists.
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [5]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

sum_of_b=b.sum()
print(sum_of_b)



33

In [9]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = b.min()
print(min_of_b)

3


In [10]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = b.max()
print(max_of_b)

8


In [12]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = b.mean()
print(mean_of_b)

5.5


In [14]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
b.prod()

20160

In [16]:
# Exercise 6 - refactor the following to use numpy to find the list of squares
np.square(b)


array([[ 9, 16, 25],
       [36, 49, 64]])

In [17]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
b[b%2!=0]

array([3, 5, 7])

In [18]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
b[b%2==0]

array([4, 6, 8])

In [19]:
# Exercise 9 - print out the shape of the array b.
print(b.shape)

(2, 3)


In [ ]:
#transpose the array b.
