Use the following code to answer the questions.

In [2]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

1. How many negative numbers are there?

In [39]:
#Getting the array of negatives
a[a<0]

#Using length to check the amount of numbers in the negative array
len(a[a<0])


4

2. How many positive numbers are there?

In [6]:
len(a[a>0])

5

3.How many even positive numbers are there?

In [49]:
b = a[a % 2== 0]
b[b>0]
print(b[b>0])
len(b[b>0])



[ 4 10 12]


3

4.If you were to add 3 to each data point, how many positive numbers would there be?

In [22]:
c = a + 3
len(c[c>0])


10

5.If you squared each number, what would the new mean and standard deviation be?

In [37]:
square = a ** 2
print(square)
print(square.mean())
print(square.std())

[ 16 100 144 529   4   1   0   0   0  36   9  49]
74.0
144.0243035046516


6.A common statistical operation on a dataset is centering. 
This means to adjust the data such that the mean of the data is 0. 
This is done by subtracting the mean from each data point.
Center the data set. See this link for more on centering.

In [36]:
the_mean = a.mean()
print(the_mean)
new_mean_array =a-3
print(new_mean_array)
latest_mean = new_mean_array.mean()
print(latest_mean)

3.0
[  1   7   9  20  -5  -4  -3  -3  -3  -9   0 -10]
0.0


7. Calculate the z-score for each data point.

In [38]:
z=(a-a.mean())/(a.std())
print(z)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]
