In [2]:
import pandas as pd
import numpy as np

In [4]:
#1 How likely is it that you roll doubles when rolling two dice?
outcomes = [1, 2, 3, 4, 5, 6]
n_simulations = 10_000

die1 = np.random.choice(outcomes, size=n_simulations)
die2 = np.random.choice(outcomes, size=n_simulations)

# Each array here shares an index where index = simulation_number
die1[0:3], die2[0:3]


(array([2, 1, 2]), array([1, 1, 3]))

In [5]:
(die1 == die2).mean()

0.1689

In [ ]:
#If you flip 8 coins, what is the probability of getting exactly 3 heads? 
#What is the probability of getting more than 3 heads?

In [12]:
# Let's answer questions experimentally rather than theoretically
# What's the probability of flipping "Heads" on a coin?

# Let's flip a coin 100,000 times and figure out the probability of flipping "Heads"

# Let's find a way to represent out data
outcomes = ["Heads", "Tails"]

flips = np.random.choice(outcomes, size=(10_000, 8))



#(flips == "Heads").mean()

In [13]:
# It'll be a bit easier to check for two heads if the head = 1 and tail is 0
# might as well turn a binary into a binary

# let's say Heads is 1 and Tails is 0
outcomes = [1, 0]
flips = np.random.choice(outcomes, size=(10_000, 8))
flips[0:4]

array([[1, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 1],
       [0, 1, 1, 0, 0, 0, 0, 1],
       [1, 1, 0, 1, 1, 0, 0, 0]])

In [14]:
# axis=1 to sum across the rows, so we have as many sums as we had pairs of coin flips
num_of_heads = flips.sum(axis=1)
num_of_heads

array([4, 4, 3, ..., 4, 5, 5])

In [15]:
(num_of_heads == 3).mean()

0.2179

In [16]:
(num_of_heads > 3).mean()

0.6441

In [19]:
#3 #There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.
#Assuming that Codeup randomly selects an alumni 
#to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [ ]:
#webdevelopment to datascience 3:1
#randomly selected alumni
#odds two billboards have data science students

In [38]:
outcomes = [1, 0]
chances = np.random.choice(outcomes, size=(10_000, 2), p=[0.75, 0.25])


In [46]:
billboards = chances.sum(axis=1)

In [49]:
billboards[0:10]

array([2, 1, 2, 2, 2, 1, 2, 1, 1, 1])

In [47]:
(billboards==2).mean()

0.5636

In [57]:
poptarts = np.random.normal(1.5, 4.5,(1_000_000,5))


In [58]:
sum_of_poptarts= poptarts.sum(axis =1)

In [59]:
(sum_of_poptarts > 17).mean()

0.172213

In [60]:
poptarts = np.random.normal(loc =3, scale = 1.5,size=(1_000_000,5))

In [61]:
poptarts

array([[ 2.49581736,  2.81751463,  3.38079756,  3.12205003,  4.82817398],
       [ 0.96989198,  4.17240608,  3.04392853,  3.12932895,  3.50822498],
       [ 0.41526338,  1.15239939,  4.80332144,  2.61000581,  4.39885906],
       ...,
       [ 1.91105557,  4.27052782,  1.79384751,  2.14522845,  2.77435316],
       [ 2.66811082,  0.83423452,  6.21860356,  3.12332292,  2.11058187],
       [ 3.71763087,  7.20168667,  5.04520478, -0.24641549,  4.33226923]])

In [62]:
sum_of_poptarts = poptarts.sum(axis=1)

In [63]:
(sum_of_poptarts > 17).mean()

0.274831

In [ ]:
#Compare Heights

#Men have an average height of 178 cm and standard deviation of 8cm.
#Women have a mean of 170, sd = 6cm.
#Since you have means and standard deviations, you can use np.random.normal to generate observations.
#If a man and woman are chosen at random, P(woman taller than man)?

In [65]:
man = np.random.normal(loc = 178, scale = 8, size = (10_000, 1))
woman = np.random.normal(loc = 170, scale = 6, size = (10_000, 1))

(man< woman).mean()

0.2087

In [66]:
man[0:5],woman[0:5]

(array([[179.56940952],
        [163.03814318],
        [181.10838453],
        [167.97724459],
        [167.17522415]]),
 array([[162.04779635],
        [179.82279756],
        [173.98033232],
        [177.32577623],
        [172.88452361]]))

In [ ]:
#When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted 
#and the installation fails. What are the odds that after having 50 students download anaconda, no one has an 
#installation issue? 100 students?
#What is the probability that we observe an installation issue within the first 150 students that download anaconda?
#How likely is it that 450 students all download anaconda without an issue?

In [ ]:
#outcomes = ["good", "failed"]

In [72]:
outcomes = [0, 1]
chances_50 = np.random.choice(outcomes, size=(10_000, 50), p=[0.996, 0.004])



In [73]:
sum_of_chances_50 = chances_50.sum(axis=1)

In [74]:
(sum_of_chances_50 ==0).mean()

0.8135

In [75]:
outcomes = [0, 1]
chances_100 = np.random.choice(outcomes, size=(10_000, 100), p=[0.996, 0.004])

In [76]:
sum_of_chances_100 = chances_100.sum(axis=1)

In [77]:
(sum_of_chances_100 ==0).mean()

0.6736

In [79]:
outcomes = [0, 1]
chances_150 = np.random.choice(outcomes, size=(10_000, 150), p=[0.996, 0.004])
sum_of_chances_150 = chances_150.sum(axis=1)
(sum_of_chances_150 ==0).mean()

0.5504

In [80]:
outcomes = [0, 1]
chances_450 = np.random.choice(outcomes, size=(10_000, 450), p=[0.996, 0.004])
sum_of_chances_450 = chances_450.sum(axis=1)
(sum_of_chances_450 ==0).mean()

0.1615

In [ ]:
#There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
#However, you haven't seen a food truck there in 3 days. How unlikely is this?

#How likely is it that a food truck will show up sometime this week?



In [99]:
outcomes = [0, 1]
foodtruck = np.random.choice(outcomes, size=(10_000, 7), p=[.7, .3])
sum_of_foodtruck = foodtruck.sum(axis=1)


In [101]:
(sum_of_foodtruck ==0).mean()

0.083

In [103]:
outcomes = [0, 1]
foodtruck = np.random.choice(outcomes, size=(10_000, 3), p=[.7, .3])
sum_of_foodtruck = foodtruck.sum(axis=1)

In [104]:
(sum_of_foodtruck ==0).mean()

0.3453

In [105]:
outcomes = [0, 1]
foodtruck = np.random.choice(outcomes, size=(10_000, 4), p=[.7, .3])
sum_of_foodtruck = foodtruck.sum(axis=1)

In [106]:
(sum_of_foodtruck ==0).mean()

0.2332

In [ ]:
#if 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [108]:
n_simulations = 1_000_000
n_trials = 23
same_birthday = np.random.randint(low = 1,high = 366 , size=(n_simulations,n_trials),dtype = int)

In [109]:
same_bday = pd.DataFrame(same_birthday)

In [ ]:
no_one_shares_bday = birthdays.apply(lambda row: row.is_unique , axis=1)